adminTimeout: 1       # Timeout for how many mins bot waits to be made admin before leaving
kickDuration: 0       # Duration of how many hours a user is banned from group after being kicked
responseTimeout: 10   # Timeout for how many mins to wait with no response before kicking
botDebug: false       # Bot send debug messages
refreshPeriod: 12     # Refresh rate interval (hours)
groupLink: https://t.me/+z8h0p_22ZA1kMWRk
top100ChatID: -1001984238822