adminTimeout: 1       # Timeout for how many mins bot waits to be made admin before leaving
kickDuration: 1       # Duration of how many mins a user is banned from group after being kicked (cannot be less than 30s or else banned forever)
responseTimeout: 10   # Timeout for how many mins to wait with no response before kicking
botDebug: false       # Bot send debug messages
refreshPeriod: 12     # Refresh rate interval (hours)
groups:
  topLockers:
    link: "https://t.me/+tHaVsa1DwIxmYTE0"
    chatID: -1001984238822
    limit: 50
